services:
  postgres:
    image: 'postgres'
    container_name: 'postgresdb'
    environment:
      - 'POSTGRES_DB=employee-service'
      - 'POSTGRES_PASSWORD=donald'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - postgresql_data:/var/lib/postgresql/data

  pgadmin4:
    image: 'elestio/pgadmin'
    container_name: 'pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: donald9do@gmail.com
      PGADMIN_DEFAULT_PASSWORD: donald
      PGADMIN_LISTEN_PORT: 4000
    ports:
      - '4001:4000'
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
volumes:
  postgresql:
  postgresql_data:
