server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:mem:employee-service
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    enabled: false
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
    user.name: user
    user.password: password
file:
  upload-dir; src/main/resources/fileData